AWSTemplateFormatVersion: '2010-09-09'
Resources:
  OpenS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead  # PUBLICLY EXPOSED
  InsecureUser:
    Type: AWS::IAM::User
    Properties:
      Path: "/"
      Policies:
        - PolicyName: AdminPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
